version: "3.8"
services:
  mysql-db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: entrega1_mingeso
    ports:
      - 33061:3306
  app:
    container_name: app-web-simple
    image: angelavendano/entrega_1
    volumes:
      - cargas:/cargas
    ports:
      - "8090:8090"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/entrega1_mingeso?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
volumes:
  mysql-data:
  cargas: